GET http://localhost:3000/campaign/cqtc8jmari99bft65is0

###

POST http://localhost:3000/campaign

{
    "name": "Campaign Beta",
    "content": "change password",
    "emails": [
        "hello@teste.com",
        "bye@teste.com"
    ]
}

###

PATCH http://localhost:3000/campaign/cancel/cqtcv2eari91c349ln1g

###

DELETE http://localhost:3000/campaign/cqtc846ari99bft65ipg