GET http://localhost:3000/campaign/cqtc8jmari99bft65is0

###

POST http://localhost:3000/campaigns

{
    "name": "Campaign Alfa",
    "content": "change password",
    "emails": [
        "james@teste.com",
        "hillary@teste.com"
    ]
}